export enum ORDERS_STATUS {
  CREATED = 'CREATED',
  CONFIMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  DELIVERED = 'DELIVERED',
}

export enum PRODUCT_UNIT {
  PIECE = 'PIECE',
  BOX = 'BOX',
}

export enum PROCESS_STATUS {
  DECLINED = 'DECLINED',
  CONFIRMED = 'CONFIRMED',
}
